"""Add date_created to Template

Revision ID: f743384cb712
Revises: d3db5926afaf
Create Date: 2025-10-26 21:59:26.368776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f743384cb712'
down_revision = 'd3db5926afaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
